ARG version=8
FROM almalinux:${version}
ARG course="Devops"\
      time="120 hrs"\
      learner="Sreenivas" 
RUN echo "Hi I am ${learner}"> /tmp/test.txt
RUN echo "Hi the learner name is ${learner}"> /tmp/test1.txt
CMD ["sleep", "100"]