ARG course="Devops"\
      time="120 hrs"\
      learner="Sreenivas" 
FROM almalinux:9
RUN echo "Hi I am ${learner}"> /tmp/test.txt
RUN echo "Hi the learner name is ${learner}"> /tmp/test1.txt
CMD ["sleep", "100"]