apiVersion: v1
kind: Pod
metadata:
  name: frontend-rm
  namespace: expense
spec:
  containers:
  - name: frontend-rm
    image: nginx
    resources: 
      requests: 
        cpu: "100 m"
        memory: "68 Mi"
      limits:
        memory: "128 Mi"
        cpu: "150 m"
