kind: Service
apiVersion: v1
metadata:
  name: frontend-service
  namespace: expense
spec:
  selector:
    project: expense
    environment: dev
    component: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80